version: "3.8"

services:
  tybachallenge:
    build: .
    container_name: tybachallenge
    ports:
    - "3000:3000"
    volumes:
    - .:/app
    env_file:
    - .env
    depends_on:
    - mongo

  mongo:
   image: mongo
   container_name: tybachallenge_mongo
   ports:
    - "27017:27017"
   volumes:
    - mongo_data:/data/db

volumes:
  mongo_data:
